# Generated by Django 5.0 on 2023-12-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
